name: Build & Push Superset 5.0.0-custom

on:
  push:
    branches: [5.0.0-custom]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            BUILD_TRANSLATIONS=false
            DEV_MODE=false
            INCLUDE_CHROMIUM=true
            PY_VER=3.9
            METADATA_DB=postgresql
            ANALYTICS_DRIVERS=pymssql clickhouse-driver
            PLAYWRIGHT=true
          cache-from: type=gha
          cache-to: type=gha,mode=max