name: Build & Push Superset 5.0.0-custom

on:
  push:
    branches: [5.0.0-custom]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: chlonn/supersetzh   # 全小写，与仓库名保持一致即可

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. 检出源码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 Docker Buildx（多平台支持）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 登录到 GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. 构建并推送镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            BUILD_TRANSLATIONS=false
            DEV_MODE=false
            INCLUDE_CHROMIUM=false
            PY_VER=3.11
            METADATA_DB=postgresql
            ANALYTICS_DRIVERS=pymssql clickhouse-driver
            PLAYWRIGHT=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
